# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph.proto',
  package='graph',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bgraph.proto\x12\x05graph\"\x0e\n\x0cNullArgument\"\x17\n\x07PNLPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1a\n\nScriptPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"*\n\x12ScriptCompositions\x12\x14\n\x0c\x63ompositions\x18\x01 \x03(\t\"\x19\n\tGraphName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\tGraphJSON\x12\x0c\n\x04JSON\x18\x01 \x01(\t2\xf8\x01\n\nServeGraph\x12\x36\n\rLoadCustomPnl\x12\x0e.graph.PNLPath\x1a\x13.graph.NullArgument\"\x00\x12<\n\nLoadScript\x12\x11.graph.ScriptPath\x1a\x19.graph.ScriptCompositions\"\x00\x12\x43\n\x0fGetCompositions\x12\x13.graph.NullArgument\x1a\x19.graph.ScriptCompositions\"\x00\x12/\n\x07GetJSON\x12\x10.graph.GraphName\x1a\x10.graph.GraphJSON\"\x00\x62\x06proto3')
)




_NULLARGUMENT = _descriptor.Descriptor(
  name='NullArgument',
  full_name='graph.NullArgument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=36,
)


_PNLPATH = _descriptor.Descriptor(
  name='PNLPath',
  full_name='graph.PNLPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='graph.PNLPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=61,
)


_SCRIPTPATH = _descriptor.Descriptor(
  name='ScriptPath',
  full_name='graph.ScriptPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='graph.ScriptPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=89,
)


_SCRIPTCOMPOSITIONS = _descriptor.Descriptor(
  name='ScriptCompositions',
  full_name='graph.ScriptCompositions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='compositions', full_name='graph.ScriptCompositions.compositions', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=133,
)


_GRAPHNAME = _descriptor.Descriptor(
  name='GraphName',
  full_name='graph.GraphName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='graph.GraphName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=160,
)


_GRAPHJSON = _descriptor.Descriptor(
  name='GraphJSON',
  full_name='graph.GraphJSON',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='JSON', full_name='graph.GraphJSON.JSON', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['NullArgument'] = _NULLARGUMENT
DESCRIPTOR.message_types_by_name['PNLPath'] = _PNLPATH
DESCRIPTOR.message_types_by_name['ScriptPath'] = _SCRIPTPATH
DESCRIPTOR.message_types_by_name['ScriptCompositions'] = _SCRIPTCOMPOSITIONS
DESCRIPTOR.message_types_by_name['GraphName'] = _GRAPHNAME
DESCRIPTOR.message_types_by_name['GraphJSON'] = _GRAPHJSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NullArgument = _reflection.GeneratedProtocolMessageType('NullArgument', (_message.Message,), {
  'DESCRIPTOR' : _NULLARGUMENT,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.NullArgument)
  })
_sym_db.RegisterMessage(NullArgument)

PNLPath = _reflection.GeneratedProtocolMessageType('PNLPath', (_message.Message,), {
  'DESCRIPTOR' : _PNLPATH,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.PNLPath)
  })
_sym_db.RegisterMessage(PNLPath)

ScriptPath = _reflection.GeneratedProtocolMessageType('ScriptPath', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTPATH,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.ScriptPath)
  })
_sym_db.RegisterMessage(ScriptPath)

ScriptCompositions = _reflection.GeneratedProtocolMessageType('ScriptCompositions', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTCOMPOSITIONS,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.ScriptCompositions)
  })
_sym_db.RegisterMessage(ScriptCompositions)

GraphName = _reflection.GeneratedProtocolMessageType('GraphName', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHNAME,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.GraphName)
  })
_sym_db.RegisterMessage(GraphName)

GraphJSON = _reflection.GeneratedProtocolMessageType('GraphJSON', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHJSON,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.GraphJSON)
  })
_sym_db.RegisterMessage(GraphJSON)



_SERVEGRAPH = _descriptor.ServiceDescriptor(
  name='ServeGraph',
  full_name='graph.ServeGraph',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=190,
  serialized_end=438,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadCustomPnl',
    full_name='graph.ServeGraph.LoadCustomPnl',
    index=0,
    containing_service=None,
    input_type=_PNLPATH,
    output_type=_NULLARGUMENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadScript',
    full_name='graph.ServeGraph.LoadScript',
    index=1,
    containing_service=None,
    input_type=_SCRIPTPATH,
    output_type=_SCRIPTCOMPOSITIONS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCompositions',
    full_name='graph.ServeGraph.GetCompositions',
    index=2,
    containing_service=None,
    input_type=_NULLARGUMENT,
    output_type=_SCRIPTCOMPOSITIONS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJSON',
    full_name='graph.ServeGraph.GetJSON',
    index=3,
    containing_service=None,
    input_type=_GRAPHNAME,
    output_type=_GRAPHJSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVEGRAPH)

DESCRIPTOR.services_by_name['ServeGraph'] = _SERVEGRAPH

# @@protoc_insertion_point(module_scope)
